[package]
name = "slog-json"
version = "2.0.0-alpha1"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Json formatter for slog-rs"
keywords = ["slog", "logging", "json"]
license = "MPL-2.0"
documentation = "https://docs.rs/slog-json"
homepage = "https://github.com/slog-rs/slog"
repository = "https://github.com/slog-rs/json"
readme = "README.md"

[lib]
path = "lib.rs"

[dependencies]
slog = { git="http://github.com/slog-rs/slog", branch = "2.x.y" }
slog-serde = { git="http://github.com/slog-rs/serde", branch = "2.x.y" }
slog-stream = { git="http://github.com/slog-rs/stream", branch = "2.x.y" }
serde_json = "0.8.2"
chrono = "0.2"
