[package]
name = "slog-json"
version = "2.0.0-alpha1"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "JSON drain for slog-rs"
keywords = ["slog", "logging", "json"]
license = "MPL-2.0"
documentation = "https://docs.rs/slog-json"
homepage = "https://github.com/slog-rs/slog"
repository = "https://github.com/slog-rs/json"
readme = "README.md"

[lib]
path = "lib.rs"

[dependencies]
slog = "2.0.0-alpha1"
serde_json = "0.9"
serde = "0.9"
chrono = "0.3"
